export const SET_TITLE = 'SET_TITLE';
export const INIT_JOBS = 'INIT_JOBS';
export const INIT_JOB = 'INIT_JOB';
export const SET_ASCENDANCY = 'SET_ASCENDANCY';
export const RESET = 'RESET';
export const RESET_JOB = 'RESET_JOB';
export const RESET_JOBS = 'RESET_JOBS';
export const SET_SKILL_LEVEL = 'SET_SKILL_LEVEL';
export const SET_MODE = 'SET_MODE';
export const SET_ACTIVE = 'SET_ACTIVE';
export const SET_ACTIVE_ALT = 'SET_ACTIVE_ALT';
export const SET_GEAR_TECH = 'SET_GEAR_TECH';
export const REMOVE_GEAR_TECH = 'REMOVE_GEAR_TECH';
export const SET_CREST_TECH = 'SET_CREST_TECH';
export const REMOVE_CREST_TECH = 'REMOVE_CREST_TECH';
export const SET_SKILL_CREST = 'SET_SKILL_CREST';
export const REMOVE_SKILL_CREST = 'REMOVE_SKILL_CREST';
export const ACTIVATE_RELATED_SKILL = 'ACTIVATE_RELATED_SKILL';
export const DEACTIVATE_RELATED_SKILL = 'DEACTIVATE_RELATED_SKILL';
export const SET_DESIRED_JOB = 'SET_DESIRED_JOB';

export default {
  INIT_JOBS,
  INIT_JOB,
  SET_ASCENDANCY,
  RESET,
  RESET_JOB,
  RESET_JOBS,
  SET_TITLE,
  SET_SKILL_LEVEL,
  SET_MODE,
  SET_ACTIVE,
  SET_ACTIVE_ALT,
  SET_GEAR_TECH,
  REMOVE_GEAR_TECH,
  SET_CREST_TECH,
  REMOVE_CREST_TECH,
  SET_SKILL_CREST,
  REMOVE_SKILL_CREST,
  ACTIVATE_RELATED_SKILL,
  DEACTIVATE_RELATED_SKILL,
  SET_DESIRED_JOB,
};
