export const SET_TITLE = 'SET_TITLE';
export const INIT_JOBS = 'INIT_JOBS';
export const INIT_JOB = 'INIT_JOB';
export const SET_ASCENDANCY = 'SET_ASCENDANCY';
export const SOFT_RESET = 'SOFT_RESET';
export const SET_SKILL_LEVEL = 'SET_SKILL_LEVEL';
export const SET_MODE = 'SET_MODE';
export const SET_ACTIVE = 'SET_ACTIVE';
export const SET_ACTIVE_ALT = 'SET_ACTIVE_ALT';
export const SET_GEAR_TECH = 'SET_GEAR_TECH';
export const REMOVE_GEAR_TECH = 'REMOVE_GEAR_TECH';
export const SET_CREST_TECH = 'SET_CREST_TECH';
export const REMOVE_CREST_TECH = 'REMOVE_CREST_TECH';
export const SET_SKILL_CREST = 'SET_SKILL_CREST';
export const REMOVE_SKILL_CREST = 'REMOVE_SKILL_CREST';

export default {
  INIT_JOBS,
  INIT_JOB,
  SET_ASCENDANCY,
  SOFT_RESET,
  SET_TITLE,
  SET_SKILL_LEVEL,
  SET_MODE,
  SET_ACTIVE,
  SET_ACTIVE_ALT,
  SET_GEAR_TECH,
  REMOVE_GEAR_TECH,
  SET_CREST_TECH,
  REMOVE_CREST_TECH,
  SET_SKILL_CREST,
  REMOVE_SKILL_CREST,
};
